version: '3.4' 

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

  migrations:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes: 
      - C:\app:/app # Windows volume
    command:
      - dotnet tool install --global dotnet-ef
      - dotnet ef migrations add NewMigration